"""empty message

Revision ID: 2f60ad5ea660
Revises: 61d1c1e572e2
Create Date: 2024-07-07 18:56:50.276399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f60ad5ea660'
down_revision = '61d1c1e572e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('bike_num', sa.Integer(), nullable=False),
    sa.Column('bike_demand', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('weather')
    op.drop_table('station_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_info',
    sa.Column('station_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('station_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('station_lat', mysql.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('station_lng', mysql.DECIMAL(precision=10, scale=6), nullable=False),
    sa.Column('bike_number', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('bike_demand', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('station_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('weather',
    sa.Column('data', mysql.DATETIME(), nullable=False),
    sa.Column('T', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('U', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Ff', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('data'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('station')
    # ### end Alembic commands ###
