"""empty message

Revision ID: 61d1c1e572e2
Revises: d2475a8b8c0e
Create Date: 2024-07-05 15:48:01.224628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61d1c1e572e2'
down_revision = 'd2475a8b8c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_apt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_time', sa.DateTime(), nullable=True))
        batch_op.drop_index('phone')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=11), nullable=False))
        batch_op.create_index('phone', ['phone'], unique=True)
        batch_op.drop_column('join_time')

    op.drop_table('email_apt')
    # ### end Alembic commands ###
