"""empty message

Revision ID: 9fd4e4ead47d
Revises: 2f60ad5ea660
Create Date: 2024-07-07 18:59:02.982529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fd4e4ead47d'
down_revision = '2f60ad5ea660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station', schema=None) as batch_op:
        batch_op.add_column(sa.Column('station_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('station_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('station_lat', sa.Numeric(precision=10, scale=6), nullable=False))
        batch_op.add_column(sa.Column('station_lng', sa.Numeric(precision=10, scale=6), nullable=False))
        batch_op.add_column(sa.Column('bike_number', sa.Integer(), nullable=True))
        batch_op.alter_column('bike_demand',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('lon')
        batch_op.drop_column('bike_num')
        batch_op.drop_column('id')
        batch_op.drop_column('lat')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('lat', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('bike_num', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('lon', mysql.FLOAT(), nullable=False))
        batch_op.alter_column('bike_demand',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('bike_number')
        batch_op.drop_column('station_lng')
        batch_op.drop_column('station_lat')
        batch_op.drop_column('station_name')
        batch_op.drop_column('station_id')

    # ### end Alembic commands ###
