"""empty message

Revision ID: ea0769869969
Revises: 9fd4e4ead47d
Create Date: 2024-07-08 00:21:22.572675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea0769869969'
down_revision = '9fd4e4ead47d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('role', ['role'], unique=True)

    # ### end Alembic commands ###
