"""Fix default value for timestamp

Revision ID: fb2595f526df
Revises: ea0769869969
Create Date: 2024-07-09 15:49:28.364594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb2595f526df'
down_revision = 'ea0769869969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_apt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_apt', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
